---
# This playbook is used by ansible-pull to configure locally.

- name: Set context
  hosts: localhost
  connection: localhost
  become: true

  pre_tasks:
    - name: Update repository cache
      ansible.builtin.apt:
        update_cache: true
      changed_when: false

  tasks:
    - name: Include task file
      ansible.builtin.include_tasks: roles/tasks/packages.yml
